"""MongoDB collection names for read models."""

ARTICLES_COLLECTION = "articles"
MEDIA_COLLECTION = "media"
USERS_COLLECTION = "users"
CATEGORIES_COLLECTION = "categories"
MARKETS_COLLECTION = "markets"
LAYOUTS_COLLECTION = "layouts"
SLOTS_COLLECTION = "slots"
WIDGETS_COLLECTION = "widgets"
